version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        links:
            - php

    php:
        build: ./code
        volumes:
            - ./code:/code
        restart: unless-stopped
        links:
            - db

    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: klamath
        MYSQL_DATABASE: craft
        MYSQL_USER: klamath
        MYSQL_PASSWORD: klamath
      expose:
        - "3306"
      volumes:
        - data:/var/lib/mysql
        - ./tmp/db.sql:/docker-entrypoint-initdb.d/db.sql
      restart: unless-stopped

volumes:
  data: